### ISSUE TITLE
Prod error: no attribute seeking custody

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-MA209AProtectiveOrder#96]
```
There was an error in the CourtFormsOnline application.

The error message was:

AttributeError: 

    AttributeError: 'bool' object has no attribute 'seeking_custody'

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8361, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 50, in 
NameError: name 'A_complaint_for_protection_from_abuse_probation_copy0005' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 8122, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8642, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8429, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9137, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 27, in 
AttributeError: 'bool' object has no attribute 'seeking_custody'

The referer URL was https://apps.suffolklitlab.org/run/209a/

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8361, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 50, in 
NameError: name 'A_complaint_for_protection_from_abuse_probation_copy0005' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 8122, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8642, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8429, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9137, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 27, in 
AttributeError: 'bool' object has no attribute 'seeking_custody'

The external hostname was apps.suffolklitlab.org+
```

**Comment by nonprofittechy** [comment]
There was a brief version of Docassemble where object_checkboxes like this:

```
---
comment: |
  Changed code to list only first names of children in question id: children user is parent of, but then choices for children_of_both became their full names in this question instead of only first names - even after I added '.familiar()' to the end.
id: custody_children
question: |
  Do you need the judge to give you custody of the ${children.as_noun()}?
fields:
  - I need custody of the ${children.as_noun()} I have in common with ${other_parties.familiar()}.: requests_custody
    datatype: yesnoradio
  - Which children do you need custody of?: wants_custody_of
    show if: requests_custody
    datatype: object_checkboxes
    choices: |
      children_of_both
    object labeler: |
      lambda y: y.familiar()
    none of the above: False 
    minlength: 1
validation code: |
  if not requests_custody:
    wants_custody_of = ALPeopleList(gathered=True, auto_gather=False)```
    
    would result in a dict of bools instead of a dict of objects. Fixed now.
